apiVersion: v1
data:
  CONNECTPLUGINNAME: k8s-controller-plugin
  HEARTBEAT: "10"
  LOGLEVEL: info
  NAMESPACE: default
  SKIPTLSVERIFY: "false"
  TLSCERTIFICATEDATA: ""
  TLSENABLED: "true"
kind: ConfigMap
metadata:
  name: eda-connect-k8s-controller-env-config
