apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    eda.nokia.com/app: connect-k8s-controller
    eda.nokia.com/app-group: connect
  name: eda-connect-k8s-connectnetworkdefinition-viewer-role
rules:
- apiGroups:
  - connect.eda.nokia.com
  resources:
  - connectnetworkdefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - connect.eda.nokia.com
  resources:
  - connectnetworkdefinitions/status
  verbs:
  - get
